<section class="content">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Perfil</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form role="form" method="post" action="<?php echo $this->baseUrl ?>/perfil/edit">
            <div class="box-body">
                <div class="form-group">
                    <p class="help-block">
                            <!--<?=Zend_Auth::getInstance()->getIdentity()->Id;?>-->
                            <img src="<?=$this->baseUrl;?>/public/img/users/default.png" width="120" height="109">
                            <br />
                            <input type="file" id="exampleInputFile">
                        </p>
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Nome</label>
                    <input type="text" class="form-control" id="nome" placeholder="Nome" 
                        value="<?=Zend_Auth::getInstance()->getIdentity()->usuario;?>">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Email</label>
                    <input type="email" class="form-control" name="username" placeholder="email"
                        value="<?=Zend_Auth::getInstance()->getIdentity()->username;?>">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Senha</label>
                    <input type="password" class="form-control" name="password" placeholder="Senha"
                        value="<?=Zend_Auth::getInstance()->getIdentity()->password;?>">
                </div>
            </div>
            <!-- /.box-body -->

            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Salvar</button>
            </div>
        </form>
    </div>
</section>
