    </main>
    <!-- main -->    
    <footer role="contentinfo">
            <div class="row">
                <div class="row-content buffer clear-after">
                    <section id="top-footer">
                        <div class="widget column three">
                            <h4>Menu</h4>
                            <ul class="plain">
                                <li><a href="http://granasocial.com/">Início</a></li>
                                <li><a href="http://granasocial.com/cadastro.php">Crie sua conta</a></li>
                                <li><a href="http://granasocial.com/como-funciona.php">Como funciona?</a></li>
                                <li><a href="http://granasocial.com/faq.php">Central de Ajuda</a></li>
                                <li><a href="http://granasocial.com/contato.php">Contato</a></li>
                                <li class="menu-item">
                                    <a href="http://granasocial.com/painel_anunciantes/"><small>Login Anunciantes</small></a>
                                </li>
                            </ul>
                        </div>
                        <div class="widget column three">
                            <h4>Termos</h4>
                            <ul class="plain">
                                <li><a href="http://granasocial.com/termos-de-uso.php">Termos de Uso</a></li>
                                <li><a href="http://granasocial.com/politica-de-privacidade.php">Política de Privacidade</a></li>
                            </ul>
                        </div>

                        <div class="widget column three">
                        </div>
                        <div class="widget meta-social column three last">
                            <h4>Siga a gente!</h4>
                            <ul class="inline">
                                <li><a href="https://twitter.com/granasocial" target="_blank" class="twitter-share border-box"><i class="fa fa-twitter fa-lg"></i></a></li>
                                <li><a href="https://www.facebook.com/groups/680889425349482/" target="_blank" class="facebook-share border-box"><i class="fa fa-facebook fa-lg"></i></a></li>
                                <li><a href="https://plus.google.com/104865662165520006291" target="_blank" class="pinterest-share border-box"><i class="fa fa-google-plus fa-lg"></i></a></li>
                            </ul>
                        </div>
                        <div class="clear"></div>
                    </section>
                    <!-- top-footer -->
                    <section id="bottom-footer">
                        <p class="keep-left">© 2015 <a href="http://www.granasocial.com/" alt="Grana Social">Grana Social</a>. Todos direitos reservados.</p>
                        <p class="keep-right">Desenvolvido e hospedado pela equipe de programadores do Grana Social</p>
                    </section>
                    <!-- bottom-footer -->
                </div>
                <!-- row-content -->
            </div>
            <!-- row -->
        </footer>
    </body>
</html>